### PR TITLE
Fix CLI error caused by bundler newer than v2.3.9

### LINKED ISSUE #15: Generator crashing because README.md format that bundler generates has been changed
I'm not sure when exactly this started, but if using a newer version of bundler, the expected `gem <name>` in the README.md generated when the gem is initialized is missing, and always crashes.

https://github.com/rubocop/rubocop-extension-generator/blob/master/lib/rubocop/extension/generator/generator.rb#L140

Here is a README.md generated with `bundle gem sample` command.

```
# Sample

Welcome to your new gem! In this directory, you'll find the files you need to be able to package up your Ruby library into a gem. Put your Ruby code in the file `lib/sample`. To experiment with that code, run `bin/console` for an interactive prompt.

TODO: Delete this and the text above, and describe your gem

## Installation

Install the gem and add to the application's Gemfile by executing:

    $ bundle add sample

If bundler is not being used to manage dependencies, install the gem by executing:

    $ gem install sample

## Usage

TODO: Write usage instructions here

## Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and the created tag, and push the `.gem` file to [rubygems.org](https://rubygems.org).

## Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/sample.

## License

The gem is available as open source under the terms of the [MIT License](https://opensource.org/licenses/MIT).
```

Error log:

```
~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-extension-generator-0.4.0/lib/rubocop/extension/generator/generator.rb:162:in `patch': Cannot apply patch for rubocop-develop/README.md because (?-mix:^gem 'rubocop-develop'$) is missing (RuntimeError)
	from ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-extension-generator-0.4.0/lib/rubocop/extension/generator/generator.rb:140:in `generate'
	from ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-extension-generator-0.4.0/lib/rubocop/extension/generator/cli.rb:29:in `run'
	from ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-extension-generator-0.4.0/lib/rubocop/extension/generator/cli.rb:12:in `run'
	from ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-extension-generator-0.4.0/exe/rubocop-extension-generator:5:in `<top (required)>'
	from ~/.rbenv/versions/3.1.2/bin/rubocop-extension-generator:25:in `load'
	from ~/.rbenv/versions/3.1.2/bin/rubocop-extension-generator:25:in `<main>'
```

Versions:

```sh
$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]

$ bundler --version
Bundler version 2.3.12

$ rubocop-extension-generator --version
rubocop-extension-generator 0.4.0
```

### PR DESCRIPTION
**Pull request by nobuyo**
Fixes #15.

Since Bundler version 2.3.9, the string `gem name` is no longer included in the README.
So added condition for bundler's version and support newer instruction to add gem to Gemfile.

ref: https://github.com/rubygems/rubygems/pull/5337

### CODE REVIEW

File: lib/rubocop/extension/generator/generator.rb [hunk 1]
```diff
@@ -137,7 +137,11 @@ def self.defaults!
             gem 'rspec'
           RUBY
 
-          patch 'README.md', /^gem '#{name}'$/, "gem '#{name}', require: false"
+          if Gem::Version.new(Bundler::VERSION) >= Gem::Version.new('2.3.9')
+            patch 'README.md', /\$ bundle add #{name}$/, "\$ bundle add #{name} --require=false"
+          else
+            patch 'README.md', /^gem '#{name}'$/, "gem '#{name}', require: false"
+          end
```
Comment (koic) [inline lib/rubocop/extension/generator/generator.rb:144]: Multi-line does not seem to be expected, right?

```suggestion
          if Gem::Version.new(Bundler::VERSION) >= Gem::Version.new('2.3.9')
            patch 'README.md', /\$ bundle add #{name}\z/, "\$ bundle add #{name} --require=false"
          else
            patch 'README.md', /\Agem '#{name}'\z/, "gem '#{name}', require: false"
          end
```

Comment (nobuyo) [reply lib/rubocop/extension/generator/generator.rb:144]: Exactly.

**Comment by nobuyo** [comment]
I'm going to squash commits...

File: lib/rubocop/extension/generator/generator.rb (hunk 1 above)
Comment (nobuyo) [reply lib/rubocop/extension/generator/generator.rb:144]: Sorry I've committed this without thinking much but the regex is incorrect because `\$ bundle add #{name}` is a line, part of `README.md`. So I'll revert the commit.
